name: emu
channels:
#- conda-forge
- defaults
dependencies:
- pip
#- pywps=4.2
- jinja2
- click
- psutil
- defusedxml
# opendap support
- netcdf4
- xarray
# tests
- pytest
- pip:
  - pywps==4.2.3
  - geomet
