name: emu
channels:
#- conda-forge
- defaults
dependencies:
- pip
#- pywps=4.2
- click
- defusedxml
# opendap support
- netcdf4
- xarray
# tests
- pytest
- pip:
  - -e git+https://github.com/geopython/pywps@master#egg=pywps
  - geomet
